[workspace]
members = ["crates/leptos-blitz", "crates/leptos_blitz_macro"]
resolver = "2"

[workspace.dependencies]
leptos_blitz_macro = { path = "./crates/leptos_blitz_macro" }
leptos_hot_reload = "0.7.1"

# [package]
# name = "leptos-blitz-examples"
# version = "0.0.1"
