[package]
name = "leptos-blitz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { git = "https://github.com/leptos-rs/leptos", rev = "4d1c99c", features = [
    "csr",
] }
any_spawner = { git = "https://github.com/leptos-rs/leptos", rev = "4d1c99c", features = [
    "tokio",
] }
next_tuple = { git = "https://github.com/leptos-rs/leptos", rev = "4d1c99c" }
send_wrapper = "0.6.0"
paste = "1"
slotmap = "1.0.7"

# blitz
blitz = { git = "https://github.com/DioxusLabs/blitz", rev = "def4c90" }
blitz-dom = { git = "https://github.com/DioxusLabs/blitz", rev = "def4c90" }
style = { git = "https://github.com/DioxusLabs/stylo", rev = "10767f4" }
tokio = { version = "1.25.0", features = ["full"] }
futures-util = "0.3.30"
vello = { version = "0.1", features = ["wgpu"] }
muda = { version = "0.11.5", features = ["serde"] }
winit = { version = "0.30.2", features = ["rwh_06"] }
wgpu = "0.19"