[package]
name = "leptos-blitz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.7", features = [
    "csr",
] }
any_spawner = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.7", features = [
    "tokio",
] }
next_tuple = { git = "https://github.com/leptos-rs/leptos", branch = "leptos_0.7" }
blitz = { git = "https://github.com/DioxusLabs/blitz" }
blitz-dom = { git = "https://github.com/DioxusLabs/blitz" }
style = { git = "https://github.com/servo/stylo", rev = "039959d" }
send_wrapper = "0.6.0"
paste = "1"
tokio = { version = "1.25.0", features = ["full"] }
futures-util = "0.3.30"
vello = { version = "0.1", features = ["wgpu"] }
muda = { version = "0.11.5", features = ["serde"] }
slotmap = "1.0.7"
winit = "0.30.2"
wgpu = "0.19"